author: FaneZhao # 作者
description: Fane's blog
keyword: ZMOYI, 原创博客, Java, Golang, Linux, 全栈, 后端开发, 前端开发
favicon: http://q8mr3z1u9.bkt.clouddn.com/static/images/ico.png

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archive/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitalk

# gitment config
gitment_owner: fanezhao
gitment_repo: fanezhao.github.io
gitment_oauth_id: 595f268d984e0123456f
gitment_oauth_secret: e4c1799bc7a82448653f758927992c6217beb7cb

# gitalk config
gitalk:
  enable: true  # 默认为 false 改为 true 
  owner:  fanezhao # 写你的用户名就好了
  repo: fanezhao.github.io # 注意这个地方是存放评论的地方，写的是你的仓库名不是地址！！！
  clientId: 595f268d984e0123456f # 你创建完之后会有 一个 id 把 ID 输入到这个地方
  clientSecret: e4c1799bc7a82448653f758927992c6217beb7cb # 以上同理
  admin: fanezhao # 输入你的用户名就可以了
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en, es-ES, fr, ru, zh-CN, zh-TW
  language:

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config

baidu_analytics: true
baidu_id: bf809fdb4f2243c687ead4f074335c7c
google_analytics:
# disqus config
disqus_shortname: 

about: 
  banner: http://q8mr3z1u9.bkt.clouddn.com/static/images/about-bg.jpg
  avatar: http://q8mr3z1u9.bkt.clouddn.com/static/images/avatar.jpeg
  description: "Don't put off till tomorrow what should be done today."
  weibo_username: 
  twitter_username: 
  github_username: fanezhao
  email: fanezhao@gamil.com
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
