author: fane # 作者
description: fane's blog
keyword: Java, Golang
favicon: http://q8mr3z1u9.bkt.clouddn.com/static/images/ico.png

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: fanezhao
gitment_repo: fanezhao.github.io
gitment_oauth_id: 595f268d984e0123456f
gitment_oauth_secret: e4c1799bc7a82448653f758927992c6217beb7cb

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics:
# disqus config
disqus_shortname: 

about: 
  banner: http://q8mr3z1u9.bkt.clouddn.com/static/images/about-bg.jpg
  avatar: http://q8mr3z1u9.bkt.clouddn.com/static/images/avatar.jpeg
  description: "Don't put off till tomorrow what should be done today."
  weibo_username: 
  twitter_username: 
  github_username: fanezhao
  email: fanezhao@gamil.com
  zhihu_username: 
  douban_username: 
  linkedin_username:

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
